name: Assign Reviewer By Label
on:
  issues:
    types: [ opened ]
  pull_request:
    types:
      - unlabeled
      - labeled

jobs:
  assign-reviewer:
    runs-on: ubuntu-latest
    steps:
      - name: glen-label
        id: all-label
        uses: buildsville/assign-reviewer-by-label@v1
        with:
          token: "${{ secrets.PR_LABEL_TOKEN }}"
          labels: '[ "ALL" ]'
          reviewers: '["carsago", "seokjin8678"]'
          remove-when-no-label: "true"
