name: Issue to Slack
on:
  issues: 
    types: [opened]
    
jobs:
  create-issue: 
    name: Send issue to slack
    runs-on: ubuntu-latest 
    steps: 
    - name: Send Issue
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_ISSUE_WEBHOOK_URL }}
      if: always()
