name: Issue to Slack
on:
  issues: 
    types: [opened]
    
jobs:
  create-issue: 
    name: Send issue to slack
    runs-on: ubuntu-latest 
    steps: 
    - name: Send Issue
      uses: 8398a7/action-slack@v3
      with:
        status: custom
        custom_payload: |
          {
            attachments: [{
              color: 'success',
              text: `
                      새로운 이슈가 생성되었습니다!\n
                      Title\n
                      ${{ github.event.issue.title }}\n\n
                      
                      URL\n
                      ${{ github.event.issue.html_url }}
                    `
            }]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_ISSUE_WEBHOOK_URL }}
      if: always()
