name: Opend Issue Notification
on:
  issues:
    types: [ opened ]

jobs:
  create-issue:
    name: Send opend issue notification to slack
    runs-on: ubuntu-latest
    steps:
      - name: Send Issue
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "*새로운 이슈가 생성되었습니다!*",
              "attachments": [
                {
                  "color": "#1F7629",
                  "blocks": [
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": "*Title*\n<${{ github.event.issue.html_url }}|${{ github.event.issue.title }}>"
                      }
                    },
                    {
                      "type": "section",
                      "fields": [
                        {
                          "type": "mrkdwn",
                          "text": "*Issue number*\n#${{ github.event.issue.number }}"
                        },
                        {
                          "type": "mrkdwn",
                          "text": "*Author*\n${{ github.event.issue.user.login }}"
                        }
                      ]
                    }
                  ]
                }
              ]
            }
          env:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_ISSUE_WEBHOOK_URL }}
            SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
